---
application:
  name: "project-manager"
  project: "Project-Manager"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "Project-Manager"
  version: "4.4"
routers:
- name: "main-project-manager"
  routes:
  - application_name: "project-manager"
    paths:
    - "/*"
